apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: taskapp
type: Opaque
stringData:
  DATABASE_USER: "REPLACE_ME"
  DATABASE_PASSWORD: "REPLACE_ME"
  SECRET_KEY: "REPLACE_ME_WITH_LONG_RANDOM_STRING"
