apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: taskapp
spec:
  clusterIP: None      # headless — DNS resolves directly to pod IP, not a VIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
