[server]
control_plane ansible_host=13.62.51.193 private_ip=10.0.1.197

[agents]
worker_0 ansible_host=13.53.102.3 private_ip=10.0.1.134
worker_1 ansible_host=51.20.137.234 private_ip=10.0.1.153

[k3s_cluster:children]
server
agents
